pipeline{
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Example Build') {
           steps {
               sh 'echo start build'
           }
        }
        stage('Test') {
           steps {
               sh 'echo start test'
           }
        }
        stage('Deploy') {
           steps {
               sh 'echo start Deploy'               
           }
        }
    }
}
