pipeline{
    agent any
    // bat get cms not recognized add environemnt
    environment {
        PATH = "C:\\WINDOWS\\SYSTEM32"  
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Example Build') {
           steps {
               bat script: 'dir'
               echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
           }
        }
        stage('Test') {
        when{
            expression {
            currentBuild.result == null || currentBuild.result=='SUCCESS'
            }       
        }
           steps {
               bat script: 'echo start test'
           }
        }
        stage('Deploy') {
           steps {
               bat script: 'echo start Deploy'               
           }
        }
    }
}
